const Rooms = require("../models/rooms.models");
const uuid = require("uuid");

const data = [
    // Habitaciones Estándar
    {
        id: uuid.v4(),
        roomNumber: "101",
        roomType: "Estándar",
        pricePerNight: 50,
        maxOccupancy: 2,
        description: "Habitación estándar con cama matrimonial y baño privado.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "102",
        roomType: "Estándar",
        pricePerNight: 50,
        maxOccupancy: 2,
        description: "Habitación estándar con cama matrimonial y baño privado.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "103",
        roomType: "Estándar",
        pricePerNight: 50,
        maxOccupancy: 2,
        description: "Habitación estándar con cama matrimonial y baño privado.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "104",
        roomType: "Estándar",
        pricePerNight: 50,
        maxOccupancy: 2,
        description: "Habitación estándar con cama matrimonial y baño privado.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "105",
        roomType: "Estándar",
        pricePerNight: 50,
        maxOccupancy: 2,
        description: "Habitación estándar con cama matrimonial y baño privado.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "106",
        roomType: "Estándar",
        pricePerNight: 50,
        maxOccupancy: 2,
        description: "Habitación estándar con cama matrimonial y baño privado.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "107",
        roomType: "Estándar",
        pricePerNight: 50,
        maxOccupancy: 2,
        description: "Habitación estándar con cama matrimonial y baño privado.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "108",
        roomType: "Estándar",
        pricePerNight: 50,
        maxOccupancy: 2,
        description: "Habitación estándar con cama matrimonial y baño privado.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "109",
        roomType: "Estándar",
        pricePerNight: 50,
        maxOccupancy: 2,
        description: "Habitación estándar con cama matrimonial y baño privado.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "110",
        roomType: "Estándar",
        pricePerNight: 50,
        maxOccupancy: 2,
        description: "Habitación estándar con cama matrimonial y baño privado.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "111",
        roomType: "Estándar",
        pricePerNight: 50,
        maxOccupancy: 2,
        description: "Habitación estándar con cama matrimonial y baño privado.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "112",
        roomType: "Estándar",
        pricePerNight: 50,
        maxOccupancy: 2,
        description: "Habitación estándar con cama matrimonial y baño privado.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // Habitaciones Dobles
    {
        id: uuid.v4(),
        roomNumber: "201",
        roomType: "Doble",
        pricePerNight: 75,
        maxOccupancy: 4,
        description:
            "Habitación doble con dos camas matrimoniales y vista al jardín.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "202",
        roomType: "Doble",
        pricePerNight: 75,
        maxOccupancy: 4,
        description:
            "Habitación doble con dos camas matrimoniales y vista al jardín.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "203",
        roomType: "Doble",
        pricePerNight: 75,
        maxOccupancy: 4,
        description:
            "Habitación doble con dos camas matrimoniales y vista al jardín.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "204",
        roomType: "Doble",
        pricePerNight: 75,
        maxOccupancy: 4,
        description:
            "Habitación doble con dos camas matrimoniales y vista al jardín.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "205",
        roomType: "Doble",
        pricePerNight: 75,
        maxOccupancy: 4,
        description:
            "Habitación doble con dos camas matrimoniales y vista al jardín.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "206",
        roomType: "Doble",
        pricePerNight: 75,
        maxOccupancy: 4,
        description:
            "Habitación doble con dos camas matrimoniales y vista al jardín.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "207",
        roomType: "Doble",
        pricePerNight: 75,
        maxOccupancy: 4,
        description:
            "Habitación doble con dos camas matrimoniales y vista al jardín.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "208",
        roomType: "Doble",
        pricePerNight: 75,
        maxOccupancy: 4,
        description:
            "Habitación doble con dos camas matrimoniales y vista al jardín.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // Habitaciones Deluxe
    {
        id: uuid.v4(),
        roomNumber: "301",
        roomType: "Deluxe",
        pricePerNight: 120,
        maxOccupancy: 2,
        description:
            "Habitación deluxe con cama king-size y vistas panorámicas.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "302",
        roomType: "Deluxe",
        pricePerNight: 120,
        maxOccupancy: 2,
        description:
            "Habitación deluxe con cama king-size y vistas panorámicas.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "303",
        roomType: "Deluxe",
        pricePerNight: 120,
        maxOccupancy: 2,
        description:
            "Habitación deluxe con cama king-size y vistas panorámicas.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "304",
        roomType: "Deluxe",
        pricePerNight: 120,
        maxOccupancy: 2,
        description:
            "Habitación deluxe con cama king-size y vistas panorámicas.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "305",
        roomType: "Deluxe",
        pricePerNight: 120,
        maxOccupancy: 2,
        description:
            "Habitación deluxe con cama king-size y vistas panorámicas.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "306",
        roomType: "Deluxe",
        pricePerNight: 120,
        maxOccupancy: 2,
        description:
            "Habitación deluxe con cama king-size y vistas panorámicas.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // Habitaciones Familiares
    {
        id: uuid.v4(),
        roomNumber: "401",
        roomType: "Familiar",
        pricePerNight: 150,
        maxOccupancy: 6,
        description:
            "Habitación familiar amplia con literas y camas matrimoniales.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "402",
        roomType: "Familiar",
        pricePerNight: 150,
        maxOccupancy: 6,
        description:
            "Habitación familiar amplia con literas y camas matrimoniales.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "403",
        roomType: "Familiar",
        pricePerNight: 150,
        maxOccupancy: 6,
        description:
            "Habitación familiar amplia con literas y camas matrimoniales.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "404",
        roomType: "Familiar",
        pricePerNight: 150,
        maxOccupancy: 6,
        description:
            "Habitación familiar amplia con literas y camas matrimoniales.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "405",
        roomType: "Familiar",
        pricePerNight: 150,
        maxOccupancy: 6,
        description:
            "Habitación familiar amplia con literas y camas matrimoniales.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: uuid.v4(),
        roomNumber: "406",
        roomType: "Familiar",
        pricePerNight: 150,
        maxOccupancy: 6,
        description:
            "Habitación familiar amplia con literas y camas matrimoniales.",
        status: "available",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];

const generateRoomSeed = async () => {
    await Rooms.bulkCreate(data);
};

generateRoomSeed()
    .then(() => console.log("Rooms seeders executed succesfully!"))
    .catch((err) => console.log(err));
